name: "Gabriel Fontes"
description: Gabriel Fontes is a Brazilian software engineer and researcher working on reproducible infrastructure, open-source software, and distributed systems.
url: "https://gsfontes.com"
lang: en

default_scheme: atlas


plugins:
  - jekyll-target-blank
  - jekyll-sitemap

target-blank:
  add_css_classes: external

sass:
  style: compact

kramdown:
  syntx_highlighter: coderay


include: [".well-known"]

source: _src

collections:
  posts:
    output: true
    permalink: /blog/:name/
    name: Posts
  publications:
    output: true
    permalink: /publications/:name/
    name: Publications
    sort_by: date

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post.html"
      nav_current: "/blog/"
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "publications"
    values:
      nav_current: "/publications/"
  -
    scope:
      path: ""
    values:
      layout: "default.html"
      language: "en"
      author: "Gabriel Fontes"
